language: node_js
node_js:
  - '0.10'
rvm:
  - 2.2
branches:
  only:
  - master
before_install:
  - rvm use 2.2 --install --binary --fuzzy
  - ruby --version
before_script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@siliconrhino.io"
  - npm install -g grunt-cli
  - npm install -g bower
  - gem install bundler
  - bundle install
  - bower install
script: npm run-script deploy
env:
  global:
  - secure: lDS7DztcklPkPjLT4+7aKnHvkOyftSs7r6hQBNaqcv5ughbzNkvJoOZbNGokyqGw/Eubz7iS9fcZOyHuLotBa0uahT4shzH6zHk4KFzgQDpO1jOxt5BcuV5DtRDQSO3/PpWmCKw5YbEdY2g/z2CJM/DI81ouKBddK0Zvkb3R2HM=
notifications:
  slack:
    rooms:
      secure: NSeTEOOekRwqWq8Z3LDU4kmdHBpnjMRQcz4XNuPB767oHk4k24EJoTpb4s7Y+R3xKbX/HKZljbloGS35oX+jZT56cAzfB4AiDAsgcqnMX195C/eGiFe4GUr0mRo9Qb2uuiHinlaPPgg0lS7LFxfSt7yJ7L/rxE8LN4TV80Z2e2Q=
