# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: siliconrhino.io
description: "silicon rhino is the cto you don't have. We handle planning, architecture and implementation of your web and mobile development projects."
author:
  name: Silicon Rhino
  email: admin@siliconrhino.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siliconrhino.io" # the base hostname & protocol for your site

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 5
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

relative_permalinks: false

# Collections
collections:
  case-studies:
    output: true
    permalink: /case-study/:path/
