# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: siliconrhino.io
description: "From MVPs to APIs and complex systems, our London-based development team can help you with your technology needs"
author:
  name: Silicon Rhino
  email: support@siliconrhino.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siliconrhino.io" # the base hostname & protocol for your site

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 5
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments

relative_permalinks: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Collections
collections:
  case-studies:
    output: true
    permalink: /case-study/:path/
  technologies:
    output: true
    permalink: /technology/:path/
  careers:
    output: true
    permalink: /careers/:path/

